### ISSUE TITLE
How to uninstall the compiled installation?

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [DIGImend/uclogic-tools#9]
Hello, I compiled from the source and installed with "sudo make install".

However my tablet is not supported so I need to uninstall it. 

Any idea on how to uninstall it?

Thanks.

**Comment by spbnick** [comment]
Execute `sudo make uninstall` from the compiled source directory.

**Comment by GreatBigWhiteWorld** [comment]
Thank you very much for answering the newbie question...
